version: "3.9"
services:

  backend:
     image: backend_image:latest
     container_name: backend
     build: ./backend
     ports:
     - "5001:5000"
     volumes:
     - ./backend:/app
     environment:
       FLASK_ENV: development

  frontend:
     image: myfrontendapp_image:latest
     container_name: myfrontendapp
     build: ./myfrontendapp
     ports:
     - "8000:8000"
     volumes:
     - ./frontendapp:/usr/src/app
     depends_on:
       - backend

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    user: "root"
    # environment:
    #   - PUID=1001
    #   - PETD=1001
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100 
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    # user: "501"
    # environment:
    # - PUID=501 
    # - PGTD=501
    privileged: true
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - ./prometheus-data:/prometheus
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
    
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    # user: "501"
    ports:
      - "5000:5000"